language: objective-c
osx_image: xcode9.4
before_install:  
  - brew update
  - brew install sdl2
script:  
  - xcodebuild -project "TravisExample.xcodeproj" -scheme "TravisExample" -destination "platform=iOS Simulator,name=iPhone 6s,OS=11.2" clean build