language: objective-c
xcode_project: TravisExample.xcodeproj
xcode_scheme: TravisExample
osx_image: xcode9.4
xcode_destination: platform=iOS Simulator,OS=11.2,name=iPhone 8

#xcode_sdk: iphonesimulator11.2